### ISSUE TITLE
sendParameter hides overloaded virtual function

### ISSUE THREAD

**Issue by giuliomoro** [Cycling74/rnbo.example.vcvrack#2]
getting this:
```
rnbo_source.cpp:318:6: warning: 'RNBO::rnbomatic::sendParameter' hides overloaded virtual function [-Woverloaded-virtual]
void sendParameter(ParameterIndex index, bool ignoreValue) {
     ^
/root/Bela/projects/rnpro/rnbo/common/RNBO_PatcherInterface.h:76:16: note: hidden overloaded virtual function 'RNBO::PatcherInterface::sendParameter' declared here: different number of parameters (1 vs 2)
  virtual void sendParameter(ParameterIndex) {}
```
what's expected here?

**Comment by isabelgk** [comment]
I believe this is coming from the fact that the `RNBO::rnbomatic` class in the exported derives from `PatcherInterfaceImpl` which in turn derives from `PatcherInterface`. In the `PatcherInterface` class, there is a `virtual void` method `sendParameter(ParameterIndex)` which takes one argument. In the `rnbomatic` class, another `sendParameter` method is defined, but it takes two arguments. This is hiding the overloaded virtual function from `PatcherInterface` which gives this warning, which is benign and expected here.
