### ISSUE TITLE
Building a single plugin from multiple rnbo_source

### ISSUE THREAD

**Issue by michelezaccagnini** [Cycling74/rnbo.example.vcvrack#6]
Hello,
Is there a way to build a single plugin with multiple modules using multiple `rnbo_source`? I have three plugins at the moment and I would like to create a single plugin containing 3 modules instead, as in the [Rack Fundamentals ](https://github.com/VCVRack/Fundamental/tree/v2 ) for instance. Problem is that each one of the plugins I want to consolidate has a same-named `rnbo_source` folder. If I can just manually change the names of `rnbo_source` in a few spots to make them unique-named that would fantastic (I am just not sure where?)

**Comment by cccstbccc** [comment]
Hallo, did you have a look at: https://rnbo.cycling74.com/learn/multiple-rnbo-devices-in-one-c-project ? maybe this can get you un-stuck.

**Comment by michelezaccagnini** [comment]
> Hallo, did you have a look at: https://rnbo.cycling74.com/learn/multiple-rnbo-devices-in-one-c-project ? maybe this can get you un-stuck.

Unfortunately this does not help since the building of the plugin will not work changing the names of the sources. I am using this repo tool to compile the plugin and the naming of the rnbo generated code cannot be changed.

**Comment by cccstbccc** [comment]
maybe i do not fully understand your problem, when you do a C++ export you get a:

- rnbo_source.cpp (this name you can change)
- a folder called "rnbo"

you can copy multiple exported RNBO sources  (rnbo_source1.cpp, rnbo_source.2cpp) into one folder
you only need one "rnbo" folder

you can include all exported classes via the HOWTO above

does this maybe help ?

**Comment by cccstbccc** [comment]
this is very true for a single class and file, but for using multiple at once you need to adapt a few things (for example modify your CMakeLists.txt file), which is laid out in the above mentioned README:

 https://rnbo.cycling74.com/learn/multiple-rnbo-devices-in-one-c-project

**Comment by michelezaccagnini** [comment]
That README does not really cover my case though. I am using MSYS compiler. I can modify the Makefile along the lines of the instructions of the README you shared to include all of the renamed ``.cpp`` files. But then what do I do with the ``dependencies.json`` and ``presets.json`` files that are unique to each ``.cpp``? I tried to adapt the steps in the document to my case but it does not seem to be matching

**Comment by michelezaccagnini** [comment]
That README does not really cover my case though. I am using MSYS compiler. I can modify the Makefile along the lines of the instructions of the README you shared to include all of the renamed ``.cpp`` files. But then what do I do with the ``dependencies.json`` and ``presets.json`` files that are unique to each ``.cpp``? 
Also in the src folder I have unique ``module.cpp``, ``plugin.cpp`` and other files that are unique to each of the modules: how do I rename them?
Here is what the src folder looks like
![image](https://github.com/Cycling74/rnbo.example.vcvrack/assets/11492957/2e9a9077-33de-4ed7-a73e-26187036535d)

This is my Makefile
```RACK_DIR ?= ../..

# Exported code
FLAGS += -Irnbo-export/rnbo/code
FLAGS += -Irnbo-export/rnbo
FLAGS += -Irnbo-export/rnbo/adapters
FLAGS += -Irnbo-export/rnbo/common
FLAGS += -Irnbo-export/rnbo/src
SLUG = NLS
SOURCES += rnbo-export/Cross_seq2.cpp //three modules are included instead of the single rnbo_source
SOURCES += rnbo-export/Cross_seq3.cpp
SOURCES += rnbo-export/Trigger_logic.cpp
SOURCES += rnbo-export/rnbo/RNBO.cpp

# VCV module
FLAGS += -Isrc 
SOURCES += $(wildcard src/*.cpp)

# Include the license and module SVGs in the distribution
DISTRIBUTABLES += $(wildcard ../LICENSE*) res

include $(RACK_DIR)/plugin.mk
```

This is what the rnbo-export folder looks like with the unique .json files
![image](https://github.com/Cycling74/rnbo.example.vcvrack/assets/11492957/bd7337ab-6c62-40a8-b19d-a8ab6bea3087)

**Comment by cccstbccc** [comment]
i am afraid there is no way of automatically combining multiple RNBO source files to one plugin, you will have to take the source code of your first plugin, and then incorporate the generated source files of the other plugins yourself (as displayed in the file main.cpp in the howto)

it might get tricky when you need to combine parameters of all three generated source files, you will have to do this by yourself and maybe use the sources of the Juce adapter of the first plugin as an example
